This section is all about pandas 
pandas is used for data analysis,manipulation,data cleaning
Has two data structures

series: it is a 1-D array like object,It holds any data type 
data frame: It is a 2-D array array,size is mutable,hetrogeneous tabular data structure with labeled axes

In [21]:
#creating series from list
import pandas as pd 
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [22]:
series.iloc[0]

np.int64(1)

In [23]:
#creating series from dictionary 
dictionary={'name':'abdullah','roll_no':17,'batch':2025}
series=pd.Series(dictionary)
print(series)
print(type(series))

name       abdullah
roll_no          17
batch          2025
dtype: object
<class 'pandas.core.series.Series'>

In [24]:
print(series['name'])
series['roll_no']

abdullah

17

In [25]:
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [31]:
#now changing indexes for list 
data=[1,2,3,4,5]
indec=['a','b','c','d','e']
series=pd.Series(data,index=indec)
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [34]:
#creating data frames from dictionary of list 
data={
    'name':['abdullah','ali','hashir','ilyas'],
    'roll_no':['32','01','25','37'],
    'is_student':[True,True,True,True]
}
dataframe=pd.DataFrame(data)
print(dataframe)

       name roll_no  is_student
0  abdullah      32        True
1       ali      01        True
2    hashir      25        True
3     ilyas      37        True

In [35]:
#you can convet data frame in array
import numpy as np 
np.array(dataframe)

array([['abdullah', '32', True],
       ['ali', '01', True],
       ['hashir', '25', True],
       ['ilyas', '37', True]], dtype=object)

In [38]:
#creating dictionaries from list of dictionaries 
data=[
    {'name':'abdullah','country':'Pak','city':'kohat'},
    {'name':'ali','country':'Ireland','city':'Malakand'},
    {'name':'ilyas','country':'Pak','city':'lakki'},
    {'name':'hashir','country':'Pak','city':'Pesh'}
]
df=pd.DataFrame(data)
print(df)

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [39]:
# accessing data from data frame
df['name']

0    abdullah
1         ali
2       ilyas
3      hashir
Name: name, dtype: object

In [43]:
df['country']

0        Pak
1    Ireland
2        Pak
3        Pak
Name: country, dtype: object

 Key Differencesloc loc(Label-based): Selects data using explicit row and column labels (names).

 iloc (Integer-based): Selects data using integer positions/index (starting from 0). 

 Visual ExampleImagine you have this DataFrame named 

df.loc[101] returns Alice's row (looks for the label 101).

df.iloc[0] returns Alice's row (looks for the first row at position 0).

Slicing (Crucial Difference)df.loc[101:102] includes the stop label (102).

df.iloc[0:1] excludes the stop index (only returns row 0).

In [ ]:
df.loc[0] #selects data using explicit row and column labels

name       abdullah
country         Pak
city          kohat
Name: 0, dtype: object

In [45]:
df.loc[0][1]

C:\Users\abdul\AppData\Local\Temp\ipykernel_12368\395987507.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][1]

'Pak'

In [46]:
data=[
    {'name':'abdullah','country':'Pak','city':'kohat'},
    {'name':'ali','country':'Ireland','city':'Malakand'},
    {'name':'ilyas','country':'Pak','city':'lakki'},
    {'name':'hashir','country':'Pak','city':'Pesh'}
]
df=pd.DataFrame(data)
print(df)

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [49]:
df.iloc[1:3] #selects data using integers

    name  country      city
1    ali  Ireland  Malakand
2  ilyas      Pak     lakki

In [50]:
df.iloc[0]

name       abdullah
country         Pak
city          kohat
Name: 0, dtype: object

In [51]:
df.iloc[0][1]

C:\Users\abdul\AppData\Local\Temp\ipykernel_12368\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

'Pak'

In [53]:
#accessing a specified element
data=[
    {'name':'abdullah','country':'Pak','city':'kohat'},
    {'name':'ali','country':'Ireland','city':'Malakand'},
    {'name':'ilyas','country':'Pak','city':'lakki'},
    {'name':'hashir','country':'Pak','city':'Pesh'}
]
df=pd.DataFrame(data)
print(df)

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [54]:
df.at[1,'city']

'Malakand'

In [55]:
df.at[0,'country']

'Pak'

In [56]:
df.iat[0,0]

'abdullah'

In [57]:
df.iat[0,1]

'Pak'

In [58]:
df.iat[1,1]

'Ireland'

In [59]:
#data manipulation wth df 
data=[
    {'name':'abdullah','country':'Pak','city':'kohat'},
    {'name':'ali','country':'Ireland','city':'Malakand'},
    {'name':'ilyas','country':'Pak','city':'lakki'},
    {'name':'hashir','country':'Pak','city':'Pesh'}
]
df=pd.DataFrame(data)
print(df)

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [61]:
df['salary']=[10000,20000,30000,40000]
df

       name  country      city  salary
0  abdullah      Pak     kohat   10000
1       ali  Ireland  Malakand   20000
2     ilyas      Pak     lakki   30000
3    hashir      Pak      Pesh   40000

In [63]:
df.drop('salary',axis=1)

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [64]:
df

       name  country      city  salary
0  abdullah      Pak     kohat   10000
1       ali  Ireland  Malakand   20000
2     ilyas      Pak     lakki   30000
3    hashir      Pak      Pesh   40000

In [ ]:
#for permanently removing it use inplace=True
df.drop('salary',axis=1,inplace=True)

In [67]:
df

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [68]:
data=[
    {'name':'abdullah','country':'Pak','city':'kohat'},
    {'name':'ali','country':'Ireland','city':'Malakand'},
    {'name':'ilyas','country':'Pak','city':'lakki'},
    {'name':'hashir','country':'Pak','city':'Pesh'}
]
df=pd.DataFrame(data)
print(df)

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [69]:
#removing rows
df.drop(0)

     name  country      city
1     ali  Ireland  Malakand
2   ilyas      Pak     lakki
3  hashir      Pak      Pesh

In [70]:
df

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [71]:
df.drop(0,inplace=True)

In [72]:
df

     name  country      city
1     ali  Ireland  Malakand
2   ilyas      Pak     lakki
3  hashir      Pak      Pesh

In [73]:
data=[
    {'name':'abdullah','country':'Pak','city':'kohat'},
    {'name':'ali','country':'Ireland','city':'Malakand'},
    {'name':'ilyas','country':'Pak','city':'lakki'},
    {'name':'hashir','country':'Pak','city':'Pesh'}
]
df=pd.DataFrame(data)
print(df)

       name  country      city
0  abdullah      Pak     kohat
1       ali  Ireland  Malakand
2     ilyas      Pak     lakki
3    hashir      Pak      Pesh

In [74]:
df['salary']=[10000,20000,30000,40000]

In [75]:
df

       name  country      city  salary
0  abdullah      Pak     kohat   10000
1       ali  Ireland  Malakand   20000
2     ilyas      Pak     lakki   30000
3    hashir      Pak      Pesh   40000

In [76]:
df['salary']=df['salary']+500

In [77]:
df

       name  country      city  salary
0  abdullah      Pak     kohat   10500
1       ali  Ireland  Malakand   20500
2     ilyas      Pak     lakki   30500
3    hashir      Pak      Pesh   40500

In [79]:
#reading csv file 
df=pd.read_csv('Online Sales Data.csv')
df.head(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card

In [80]:
df.tail(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
230,10231,2024-08-18,Clothing,Adidas Originals Trefoil Hoodie,4,64.99,259.96,Asia,Debit Card
231,10232,2024-08-19,Books,Dune by Frank Herbert,2,9.99,19.98,North America,Credit Card
232,10233,2024-08-20,Beauty Products,Fresh Sugar Lip Treatment,1,24.00,24.00,Europe,PayPal
233,10234,2024-08-21,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card
234,10235,2024-08-22,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [83]:
print(df.dtypes)

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [85]:
print(df.describe())

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000